## numpy

In [1]:
import numpy as np

Q.1.1  
★ 1,2,3,4の配列を作れ

In [2]:
array = np.array([1, 2, 3, 4])
print(array)

[1 2 3 4]


Q.1.2  
★以下の２次元配列を作れ  
1,2,4  
8,16,32

In [3]:
array = np.array([[1, 2, 4],[8, 16, 32]])
print(array)

[[ 1  2  4]
 [ 8 16 32]]


Q.1.3  
★1,2,3,4,5,6の配列を作り、2行3列に変換せよ

In [4]:
array = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(array)

[[1 2 3]
 [4 5 6]]


Q.1.4  
★1,2,3,4,5,6の配列を作り、6行1列に変換せよ

In [5]:
array = np.array([1, 2, 3, 4, 5, 6]).reshape(6, 1)
print(array)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


Q.1.5  
★以下の２次元配列を作り、1次元配列に変換せよ  
1,2,4  
8,16,32

In [6]:
array = np.array([[1, 2, 4],[8, 16, 32]]).flatten()
print(array)

[ 1  2  4  8 16 32]


Q.1.6  
★以下の２次元配列を作り、何行何列か調べよ  
1,2,4  
8,16,32

In [7]:
array = np.array([[1, 2, 4],[8, 16, 32]])
print(array.shape)

(2, 3)


Q.1.7  
★以下の２次元配列を作り、次元数を調べよ  
1,2,4  
8,16,32

In [8]:
array = np.array([[1, 2, 4],[8, 16, 32]])
print(array.ndim)

2


Q.1.8  
★以下の２次元配列を作り、要素数を調べよ  
1,2,4  
8,16,32

In [9]:
array = np.array([[1, 2, 4],[8, 16, 32]])
print(array.size)

6


Q.2.1  
★1-100までの配列を作成せよ

In [10]:
array = np.arange(1, 101)
print(array)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


Q.2.2  
★以下の２次元配列を作れ  
0,0,0,0,0  
0,0,0,0,0

In [11]:
array = np.zeros(10).reshape(2, 5)
print(array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Q.2.3  
★3行4列の0-1の乱数の配列を作れ

In [12]:
array = np.random.rand(3, 4)
print(array)

[[0.21804385 0.24756944 0.64813671 0.38607521]
 [0.1552441  0.85147188 0.03044728 0.21149929]
 [0.18856668 0.25871464 0.9888802  0.83797144]]


Q.3.1  
★1,2,4の配列と8,16,32の配列を作り、2つの配列を結合し1,2,4,8,16,32の配列を作れ

In [13]:
# np.append
array_1 = np.array([1,2,4])
array_2 = np.array([8,16,32])
array_3 = np.append(array_1, array_2)
print(array_3)

[ 1  2  4  8 16 32]


Q.3.2  
★以下の２次元配列を作り、2行1列の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [14]:
array = np.arange(1,10).reshape(3,3)
print(array[1,0])

4


Q.3.3    
★以下の２次元配列を作り、最終行最終列の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [15]:
array = np.arange(1,10).reshape(3,3)
print(array[-1,-1])

9


Q.3.4    
★以下の２次元配列を作り、1行目の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [16]:
array = np.arange(1,10).reshape(3,3)
print(array[0,:])

[1 2 3]


Q.3.5    
★以下の２次元配列を作り、3行1-2列の要素を切り出せ  
1,2,3  
4,5,6  
7,8,9

In [17]:
array = np.arange(1,10).reshape(3,3)
print(array[2,0:2])

[7 8]


Q.3.1  
★ 以下の計算をせよ（ブロードキャストを利用しても良い）  

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) + \left(\begin{array}{ccc} 1 & 1 & 1\\ 1 & 1 & 1 \\ \end{array}\right)$

In [18]:
array = np.arange(1,7).reshape(2,3)
print(array + 1)

[[2 3 4]
 [5 6 7]]


Q.3.2  
★ 以下の計算をせよ（ブロードキャストを利用しても良い）  

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) - \left(\begin{array}{ccc} 1 & 2 & 3\\ 1 & 2 & 3 \\ \end{array}\right)$

In [19]:
array_1 = np.arange(1,7).reshape(2,3)
array_2 = np.array([1,2,3])
print(array_1 - array_2)

[[0 0 0]
 [3 3 3]]


Q.3.3  
★ 以下の計算をせよ（ブロードキャストを利用しても良い）  

$\displaystyle 3\left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) - 2\left(\begin{array}{ccc} 1 & 2 & 3\\ 1 & 2 & 3 \\ \end{array}\right)$

In [20]:
array_1 = np.arange(1,7).reshape(2,3)
array_2 = np.array([1,2,3])
print(3 * array_1 - 2 * array_2)

[[ 1  2  3]
 [10 11 12]]


Q.3.4  
★ 以下の内積を計算せよ  

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right) \left(\begin{array}{ccc} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{array}\right)$

In [21]:
array_1 = np.arange(1,7).reshape(2,3)
array_2 =np.arange(1,7).reshape(3,2)
print(array_1)
print()
print(array_2)
print()
print(np.dot(array_1, array_2))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[22 28]
 [49 64]]


Q.4.1  
★ 以下の2次元配列をそれぞれ行方向と列方向に合計した１次元配列を求めよ 

$\displaystyle \left(\begin{array}{ccc} 1 & 2 & 3\\ 4 & 5 & 6 \\ \end{array}\right)$

In [22]:
array = np.arange(1,7).reshape(2,3)
print(array)
print()

array_0 = np.sum(array, axis=0)
print(array_0)
print()

array_1 = np.sum(array, axis=1)
print(array_1)

[[1 2 3]
 [4 5 6]]

[5 7 9]

[ 6 15]


Q.5.1  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（シグモイド関数）  
$\displaystyle{f(x)=\frac{1}{(1+\exp(-x))}}$

In [23]:
# ヒント  
array = np.array([0,1,2])
print(np.exp(array))

[1.         2.71828183 7.3890561 ]


In [24]:
def sigmoid(x):
    
    return 1 / (1 + np.exp(-x))

array = np.array([-1,0,1,2])
print(sigmoid(array))

[0.26894142 0.5        0.73105858 0.88079708]


Q.5.2  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ステップ関数）  
$f(x)=1  (x>0)$  
$f(x)=0  (x\le0)$

In [25]:
# ヒント
array = np.array([-1,0,1,2])
print(array > 0)
print(np.array([True, False]).astype(int))

[False False  True  True]
[1 0]


In [26]:
def step(x):
    
    return (x > 0).astype(int)

array = np.array([-1,0,1,2])
print(step(array))

[0 0 1 1]


Q.5.3  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ReLU関数）  
$f(x)=x  (x>0)$  
$f(x)=0  (x\le0)$

In [27]:
# ヒント
array = np.array([-1,0,1,2])
print(np.maximum(1, array))

[1 1 1 2]


In [28]:
def relu(x):
    
    return np.maximum(0, x)

array = np.array([-1,0,1,2])
print(relu(array))

[0 0 1 2]


Q.5.4  
★★1次元の引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ソフトマックス関数）  
$\displaystyle f(x_k)=\frac{\exp(x_k)}{\sum_{i=1}^{n}\exp(x_i)}$  


In [29]:
# ヒント
array = np.array([1,2,3])
np.sum(array)

6

In [30]:
def softmax(x):   
    
    exp = np.exp(x)

    return exp / np.sum(exp)

array = np.array([1,2,3])
print(softmax(array))

[0.09003057 0.24472847 0.66524096]


Q.5.5  
★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ソフトマックス関数）  
$\displaystyle f(x_k)=\frac{\exp(x_k)}{\sum_{i=1}^{n}\exp(x_i)}$  


In [31]:
# ヒント
array = np.array([[1,2,3],[4,5,6]])
np.sum(array, axis=1)

array([ 6, 15])

In [32]:
def softmax(x):   
    
    exp = np.exp(x)
    
    if x.ndim == 1:
        return exp / np.sum(exp)

    # reshape(-1, 1)してn行1列にしないとうまくブロードキャストできない
    # print(np.sum(exp, axis=1))
    # print(np.sum(exp, axis=1).reshape(-1, 1)) 
    return exp / np.sum(exp, axis=1).reshape(-1, 1)

array = np.array([[1,2,3],[4,5,6]])
print(softmax(array))

[[0.09003057 0.24472847 0.66524096]
 [0.09003057 0.24472847 0.66524096]]


Q.5.6  
★★★引数を配列で受け取り、各要素について以下の関数の結果を返す関数を実装せよ（ソフトマックス関数）  
$\displaystyle f(x_k)=\frac{\exp(x_k)}{\sum_{i=1}^{n}\exp(x_i)}$  
ただし、要素が大きいと上記数式のソフトマックス関数はオーバーフローしてしまう。  
配列から配列の最大値を引くオーバーフロー対策をせよ。

In [33]:
def softmax(x):   
    
    exp = np.exp(x)
    
    if x.ndim == 1:
        return exp / np.sum(exp)

    return exp / np.sum(exp, axis=1).reshape(-1, 1)


def fixed_softmax(x):   
    
    exp = np.exp(x - np.max(x))

    if x.ndim == 1:
        return exp / np.sum(exp)

    return exp / np.sum(exp, axis=1).reshape(-1, 1)

array = np.array([1,2,3])
print(softmax(array))
print(fixed_softmax(array))
print()

array = np.array([10000,10001,10002])
print(softmax(array))
print(fixed_softmax(array))


[0.09003057 0.24472847 0.66524096]
[0.09003057 0.24472847 0.66524096]

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


/Users/suzuki/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: overflow encountered in exp
  app.launch_new_instance()
/Users/suzuki/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/ipykernel/__main__.py:6: RuntimeWarning: invalid value encountered in true_divide


Q.6.1  
★★まとめ問題  
文章の単語の共起行列からコサイン類似度を求めたい  
参考：https://public-constructor.com/co-occurence-matrix-and-vector-cosine-similarity/  
以下の数式を参考に、ベクトルを2つ引数で取り、コサイン類似度を求めるget_cos_similarity関数を実装せよ。  

<コサイン類似度>  
$\displaystyle \overrightarrow{a}=(a_1,a_2,\cdots,a_n)$,$\overrightarrow{b}=(b_1,b_2,\cdots,b_n)$の時、  

$\displaystyle \dfrac{a_1b_1+\cdots +a_nb_n}{\sqrt{a_1^2+\cdots +a_n^2}\sqrt{b_1^2+\cdots +b_n^2}}$


また、以下の設計図とjupyterのコードを参考にして、コサイン類似度を求めるクラスを作成せよ  

In [34]:
# ヒント  
print("abc".replace("b", "z")) # replaceで置き換えることができる　　
print()
print("a,b,c".split(",")) # splitで分割したリストを作成することができる  
print()

array = np.array([1,2,3])
print(np.sqrt(array)) # ルートを計算できる　　
print()
print(array**2) # 二乗を計算できる

azc

['a', 'b', 'c']

[1.         1.41421356 1.73205081]

[1 4 9]


In [35]:
# 設計図  
#class CoOccurrenceMatrix:
    
    # ＜コンストラクタ＞
    # 文章を引数として受け取り、共起行列を作成してインスタンス変数に保存する
    
    #＜メソッド＞
    #  2つの単語を引数としてとり、コサイン類似度を計算して返却する    

In [36]:
# 以下、jupyterコード

In [37]:
text = "If you can dream it, you can do it."

In [38]:
# 文章の前処理
words = text.lower().replace(".", " .").replace(",", " ,").split(" ")
print(words)

['if', 'you', 'can', 'dream', 'it', ',', 'you', 'can', 'do', 'it', '.']


In [39]:
# コーパスの作成
word_to_id = {}
id_to_word = {}
corpus = []
for word in words:
    if word not in word_to_id:
        idx = len(word_to_id)
        word_to_id[word] = idx
        id_to_word[idx] = word
        
    corpus.append(word_to_id[word])

print(word_to_id)
print(id_to_word)
print(corpus)

{'you': 1, 'do': 6, '.': 7, 'it': 4, 'if': 0, 'dream': 3, 'can': 2, ',': 5}
{0: 'if', 1: 'you', 2: 'can', 3: 'dream', 4: 'it', 5: ',', 6: 'do', 7: '.'}
[0, 1, 2, 3, 4, 5, 1, 2, 6, 4, 7]


In [40]:
# 共起行列を作成
word_size = len(set(corpus))
matrix = np.zeros((word_size, word_size))

for idx, word_id in enumerate(corpus):
    
    left_idx = idx - 1
    right_idx = idx + 1
    
    if left_idx >= 0:
        left_word_id = corpus[left_idx]
        matrix[word_id, left_word_id] += 1

    if right_idx < len(corpus):
        right_word_id = corpus[right_idx]
        matrix[word_id, right_word_id] += 1

print(matrix)

[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 2. 0. 0. 1. 0. 0.]
 [0. 2. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]


In [41]:
# 詳細に確認
header = ""
detail = ""
for idx, row in enumerate(matrix):
    header = header + id_to_word[idx] + " "
    detail = detail + "{}\n{}\n".format(id_to_word[idx], row) 

print(words)
print()
print(header)
print()
print(detail)    

['if', 'you', 'can', 'dream', 'it', ',', 'you', 'can', 'do', 'it', '.']

if you can dream it , do . 

if
[0. 1. 0. 0. 0. 0. 0. 0.]
you
[1. 0. 2. 0. 0. 1. 0. 0.]
can
[0. 2. 0. 1. 0. 0. 1. 0.]
dream
[0. 0. 1. 0. 1. 0. 0. 0.]
it
[0. 0. 0. 1. 0. 1. 1. 1.]
,
[0. 1. 0. 0. 1. 0. 0. 0.]
do
[0. 0. 1. 0. 1. 0. 0. 0.]
.
[0. 0. 0. 0. 1. 0. 0. 0.]



In [42]:
def get_cos_similarity(a, b):
    ### ここに実装せよ
    return np.dot(a, b) / (np.sqrt(np.sum(a**2)) * np.sqrt(np.sum(b**2)))

In [43]:
# コサイン類似度を求める
vec_a = matrix[word_to_id["you"]]
vec_b = matrix[word_to_id["it"]]

get_cos_similarity(vec_a, vec_b)

0.20412414523193154

In [44]:
### 以下にクラスを書け

In [45]:
class CoOccurrenceMatrix:
    
    def __init__(self, text):
        
        words = text.lower().replace(".", " .").replace(",", " ,").split(" ")
        word_to_id = {}
        id_to_word = {}
        corpus = []
        for word in words:
            if word not in word_to_id:
                idx = len(word_to_id)
                word_to_id[word] = idx
                id_to_word[idx] = word

            corpus.append(word_to_id[word])
            
        word_size = len(set(corpus))
        matrix = np.zeros((word_size, word_size))


        for idx, word_id in enumerate(corpus):

            left_idx = idx - 1
            right_idx = idx + 1

            if left_idx >= 0:
                left_word_id = corpus[left_idx]
                matrix[word_id, left_word_id] += 1

            if right_idx < len(corpus):
                right_word_id = corpus[right_idx]
                matrix[word_id, right_word_id] += 1
        
        self.matrix = matrix
        
        
    def get_cos_similarity(self, word_a, word_b):
        
        vec_a = self.matrix[word_to_id[word_a]]
        vec_b = self.matrix[word_to_id[word_b]]
        
        return  np.dot(vec_a, vec_b) / (np.sqrt(np.sum(vec_a**2)) * np.sqrt(np.sum(vec_b**2)))
        
model = CoOccurrenceMatrix("If you can dream it, you can do it.")
model.get_cos_similarity("you", "it")

0.20412414523193154